# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField(default=0)),
                ('quantity', models.IntegerField()),
                ('product_name', models.CharField(max_length=120)),
                ('quality', models.CharField(default=0, max_length=120)),
                ('price', models.IntegerField(default=0)),
                ('catigory', models.CharField(blank=True, default='seller', max_length=10)),
                ('is_sent', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
