# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
