# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('product_name', models.CharField(max_length=120)),
                ('quality', models.CharField(default=0, max_length=120)),
                ('price', models.IntegerField(default=0)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
