# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-15 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
